version: 2
jobs:
    build:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run: echo "build"
    test:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run: echo "test"
workflow:
    version: 2
    build_test:
        jobs:
            - build
            - test